project:
  type: website
  output-dir: docs

website:
  title: "Yongjin Lee"
  navbar:
    left:
      - research.qmd
      - teaching.qmd
      - cv.qmd
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

